# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\x12\x05myapp\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\'\n\x0cTextResponse\x12\x17\n\x0fpredicted_label\x18\x01 \x01(\t2K\n\x11PredictionService\x12\x36\n\x0bPredictText\x12\x12.myapp.TextRequest\x1a\x13.myapp.TextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEXTREQUEST']._serialized_start=20
  _globals['_TEXTREQUEST']._serialized_end=47
  _globals['_TEXTRESPONSE']._serialized_start=49
  _globals['_TEXTRESPONSE']._serialized_end=88
  _globals['_PREDICTIONSERVICE']._serialized_start=90
  _globals['_PREDICTIONSERVICE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
